### ISSUE TITLE
Buildings Coverage 

### ISSUE THREAD

**Issue by PavlosDem99** [OvertureMaps/data#107]
Hello, first of all congratulations to all the OMF team for this incredible work. I just downloaded the buildings dataset for Cyprus and I wanted to compare it with the Microsoft Buildings dataset which I have downloaded it months ago. I figured out that a lot of buildings of the OMF dataset are missing compared to Microsoft's. This is odd, while the OMF buildings dataset come from Microsoft, OSM and ESRI (at least the release 07-26). 

<img width="1238" alt="image" src="https://github.com/OvertureMaps/data/assets/95135614/ee924daf-7614-4c66-8330-b5fa1a0b56f2">

<img width="1249" alt="image" src="https://github.com/OvertureMaps/data/assets/95135614/5d06e02f-d900-4bee-a8f5-bac0d25398d6">

<img width="152" alt="image" src="https://github.com/OvertureMaps/data/assets/95135614/b19104cc-fb8b-4750-ad77-d838fedd8704">

I am curious why all Microsoft buildings of Cyprus does not exist in the OMF building's dataset?

**Comment by jwass** [comment]
Hi @PavlosDem99 - Can you post the area (bounding box or similar) of the area of this screenshot? And also which Overture release this includes?

**Comment by jenningsanderson** [comment]
Hi, @PavlosDem99, please take a look at the latest Overture data release from December 2023. I just confirmed that the OSM and MSFT data are both in there for Cyprus.

If you notice any further discrepancies, please do reach out, would love to troubleshoot them!

**Comment by PavlosDem99** [comment]
> Hi, @PavlosDem99, please take a look at the latest Overture data release from December 2023. I just confirmed that the OSM and MSFT data are both in there for Cyprus.
> 
> If you notice any further discrepancies, please do reach out, would love to troubleshoot them!

Thanks for your reply @jenningsanderson @jwass. I used 07/26 release, so the problem may be because I didn't use the new one from December 2023. Unfortunately, I can't use the December release because I am using Apache Sedona.
https://github.com/wherobots/OvertureMaps/issues/4#issuecomment-1877967146

**Comment by jwass** [comment]
@PavlosDem99 Reading that comment, it looks like you're now able to access the December data?

Separately we are looking to improve the spatial indexing in the next few releases so stay tuned for that.

**Comment by PavlosDem99** [comment]
> @PavlosDem99 Reading that comment, it looks like you're now able to access the December data?
> 
> Separately we are looking to improve the spatial indexing in the next few releases so stay tuned for that.

My mistake ... I can use it but it is extremely slow as Jia says. Therefore I will wait the future releases.
