### ISSUE TITLE
Consider collaborating with Snap Inc. (Snapchat)

### ISSUE THREAD

**Issue by upintheairsheep** [OvertureMaps/data#109]
Hello, can the Overture team invite Snap Inc. to join the Coalition? Snap has lots of location and geography information while it lacks places that Snapchat is not oftenly used. Snap would be if it with Overture’s places and we would be bigot from Snapchat’s businesses.

**Comment by bglazer-meta** [comment]
Thanks for the suggestion. Overture is open to anyone, Snap would be a great addition. We'd love for Snap to initiate a conversation.

**Comment by upintheairsheep** [comment]
> Thanks for the suggestion. Overture is open to anyone, Snap would be a great addition. We'd love for Snap to initiate a conversation.

Have you informed the Snap team about Overture yet?

**Comment by upintheairsheep** [comment]
> Thanks for the suggestion. Overture is open to anyone, Snap would be a great addition. We'd love for Snap to initiate a conversation.

also HERE would be nice to join as well.

**Comment by bglazer-meta** [comment]
Thanks for the suggestion. We'd love for HERE to join as well.
Folks on the Overture team have contacts within both companies, and both companies are aware of Overture.

**Comment by upintheairsheep** [comment]
Imagine Google and Apple themselves joining…

**Comment by upintheairsheep** [comment]
> Thanks for the suggestion. We'd love for HERE to join as well.
> Folks on the Overture team have contacts within both companies, and both companies are aware of Overture.

Hello, have you also tried inviting 

> Thanks for the suggestion. We'd love for HERE to join as well.
> Folks on the Overture team have contacts within both companies, and both companies are aware of Overture.

https://en.wikipedia.org/wiki/List_of_online_map_services - have you tried having these partners added as well, like local services likecBaidu, QQ/Tencent,  Naver, and Yandex for instance
