### ISSUE TITLE
Make links in README.md clickable

### ISSUE THREAD

**Issue by jidanni** [OvertureMaps/data#114]
1. Visit https://github.com/OvertureMaps/data/tree/main
2. See URLs like https://overturemapswestus2.blob.core.windows.net/release/2024-01-17-alpha.0/theme=admins
3. Wonder why not clickable? Yes, clickable above, but not there in (1).

**Comment by jenningsanderson** [comment]
Good question!
Those are paths to specific locations that are not intended to be explored in a browser, so they are not hyperlinks. I will keep a close eye on other paths, however, and ensure that we make hyperlinks where appropriate.  Thanks!
