### ISSUE TITLE
Data - Research project on shrinking cities

### ISSUE THREAD

**Issue by eszymczyk** [OvertureMaps/data#132]
Dear team,

I am conducting a research project on urban shrinkage, which is being funded by the NCN Polish National Science Center. The objective of my research is to gain knowledge about the spatial relationships of shrinking cities. I analyse the connections between cities and the national road network to uncover patterns of shrinkage and location. For this purpose, I require historical road data from both Germany and Poland. Could you please let me know if you can assist me in obtaining this data, and who I should get in touch with for further details?

Best,
Ewa

**Comment by jwass** [comment]
Hi @eszymczyk - as interesting as that research sounds Overture doesn't plan to deliver historical road data. While our past deliveries should always be available to see how they change, I don't believe that's the timeframe you're looking for.
