### ISSUE TITLE
Readme SQL error

### ISSUE THREAD

**Issue by om2468** [OvertureMaps/data#136]
I ran the sql for duckdb in the page:
https://github.com/OvertureMaps/data/blob/main/README.md#how-to-access-overture-maps-data

The line currently is:         
`id as areaId, `
I think it needs to be
`id as area_id, `
given the change from camel case.

**Comment by jwass** [comment]
Thanks @om2468! This was fixed in https://github.com/OvertureMaps/data/pull/133/ which removes most of the documentation from the readme here and points people to the official docs
