### ISSUE TITLE
Missing all type=infrastructure data?

### ISSUE THREAD

**Issue by tjwebb** [OvertureMaps/data#140]
In base, there is data for land, land_use, and water -- but infrastructure is absent. Why is this?

https://docs.overturemaps.org/schema/reference/base/infrastructure

```
aws s3 ls s3://overturemaps-us-west-2/release/2024-03-12-alpha.0/theme=base/
                           PRE type=land/
                           PRE type=land_use/
                           PRE type=water/
```

**Comment by jwass** [comment]
The infrastructure theme has been added since that 2024-03-12 release. You'll see the data in the next release very soon.

**Comment by tjwebb** [comment]
ok thanks!

**Comment by jwass** [comment]
So "very soon" in my message above meant "in just a few hours". Infrastructure data is in today's release:

```
select count(1)
from overture_2024_04_16_beta_0
where theme = 'base'
	and type = 'infrastructure'
```

has 48080802 rows.

I'll close this but feel free to reopen or make a new issue if any problems
