### ISSUE TITLE
GERS link in README leads nowhere

### ISSUE THREAD

**Issue by tjwebb** [OvertureMaps/data#142]
This is a dead link: https://docs.overturemaps.org/gers/

**Comment by ImreSamu** [comment]
@tjwebb 
Check the https://docs.overturemaps.org/guides/gers/

**Comment by danabauer** [comment]
The correct link to the GERS guide is https://docs.overturemaps.org/guides/gers

**Comment by varapmsft** [comment]
Fixed the link in ReadMe.
