### ISSUE TITLE
overture.release.v2024_04_16_beta_0 on Athena not returning expected results

### ISSUE THREAD

**Issue by acgeospatial** [OvertureMaps/data#143]
Creating an issue from feedback here https://github.com/OvertureMaps/data/discussions/1#discussioncomment-9149333 as its been locked and I cannot comment.

This query 

```sql
SELECT id,
class,
CAST(sources AS JSON) AS sources,
sources[1].dataset AS primary_source,
CAST(names AS JSON) AS names,
ST_GeomFromBinary(geometry) AS geometry
FROM
overture.release.v2024_04_16_beta_0
WHERE theme='places'
AND type='place'
AND bbox.xmin > -122.44
AND bbox.xmax < -122.25
AND bbox.ymin > 47.56
AND bbox.ymax < 47.71
```

Currently returns 2 records. I am expecting 1000's as was the case on the overture.release.v2024_03_12_alpha_0 release

If I am honest I'm not interested in the outcome of this query (but its in the docs so probably should work https://docs.overturemaps.org/getting-data/cloud-services/#13/47.6/-122.33/0/45), its just I see the issue persisting across my road queries. eg

```sql
SELECT
    level,
    JSON_EXTRACT_SCALAR(road, '$.class') AS road_class,
    JSON_EXTRACT_SCALAR(road, '$.roadNames.common[0].value') AS road_name,
    JSON_EXTRACT_SCALAR(road, '$.restrictions.speed_limits[0].max_speed[0]') AS max_speed,
    sources[1].dataset AS source,
    ST_ASTEXT(ST_GeomFromBinary(geometry)) as geometry_wkt
FROM overture.release.v2024_04_16_beta_0
WHERE theme = 'transportation' AND type = 'segment'
    AND bbox.xmin > 102.01 AND bbox.xmax < 109.45
    AND bbox.ymin > 8.33 AND bbox.ymax < 23.46
    AND (JSON_EXTRACT_SCALAR(road, '$.class') = 'motorway' OR JSON_EXTRACT_SCALAR(road, '$.class') = 'primary' OR JSON_EXTRACT_SCALAR(road, '$.class') = 'trunk' OR JSON_EXTRACT_SCALAR(road, '$.class') = `'secondary');
```

This returns me 0 records. Again expecting 1000's

The change (aside from the release) is the change in the bbox.xmin bbox.xmax etc

```sql
    AND bbox.xmin > 102.01 AND bbox.xmax < 109.45
    AND bbox.ymin > 8.33 AND bbox.ymax < 23.46
```

**Comment by jwass** [comment]
@acgeospatial It looks like some folks tracked down an issue related to Athena here including from the original discussion https://github.com/OvertureMaps/data/discussions/1#discussioncomment-9149333

Have you been able to retry (or try the suggested solution) to see if it fixes the issue?

**Comment by acgeospatial** [comment]
@jwass thanks for the help and comments. I'm still having the issue I think.

`SELECT
    level,
    JSON_EXTRACT_SCALAR(road, '$.class') AS road_class,
    JSON_EXTRACT_SCALAR(road, '$.roadNames.common[0].value') AS road_name,
    JSON_EXTRACT_SCALAR(road, '$.restrictions.speed_limits[0].max_speed[0]') AS max_speed,
    sources[1].dataset AS source,
    ST_ASTEXT(ST_GeomFromBinary(geometry)) as geometry_wkt
FROM overture.release.v2024_03_12_alpha_0
WHERE theme = 'transportation' AND type = 'segment'
    AND bbox.minX > 119.43 AND bbox.maxX < 125.13
    AND bbox.minY > 12.09 AND bbox.maxY < 18.92
    AND (JSON_EXTRACT_SCALAR(road, '$.class') = 'motorway' OR JSON_EXTRACT_SCALAR(road, '$.class') = 'primary' OR JSON_EXTRACT_SCALAR(road, '$.class') = 'trunk' OR JSON_EXTRACT_SCALAR(road, '$.class') = 'secondary');`

will return me 86,269 on the beta

on the alpha

`SELECT
    level,
    JSON_EXTRACT_SCALAR(road, '$.class') AS road_class,
    JSON_EXTRACT_SCALAR(road, '$.roadNames.common[0].value') AS road_name,
    JSON_EXTRACT_SCALAR(road, '$.restrictions.speed_limits[0].max_speed[0]') AS max_speed,
    sources[1].dataset AS source,
    ST_ASTEXT(ST_GeomFromBinary(geometry)) as geometry_wkt
FROM overture.release.v2024_04_16_beta_0
WHERE theme = 'transportation' AND type = 'segment'
    AND bbox.xmin > 119.43 AND bbox.xmax < 125.13
    AND bbox.ymin > 12.09 AND bbox.ymax < 18.92
    AND (JSON_EXTRACT_SCALAR(road, '$.class') = 'motorway' OR JSON_EXTRACT_SCALAR(road, '$.class') = 'primary' OR JSON_EXTRACT_SCALAR(road, '$.class') = 'trunk' OR JSON_EXTRACT_SCALAR(road, '$.class') = 'secondary');`

gets me 0. I'm sure its me, what what have I done wrong between versions?
