### ISSUE TITLE
Excess properties in theme=divisions/type=division

### ISSUE THREAD

**Issue by ComeTogether1** [OvertureMaps/data#177]
It seems **[division](https://docs.overturemaps.org/schema/reference/divisions/division/)** parquets have excess properties derived from **[Boundary](https://docs.overturemaps.org/schema/reference/divisions/boundary/)** such as class, divisions and is_disputed that aren't declared in the schema. 

D SELECT * FROM read_parquet('/mnt/alpha/overture-2024-06-13-beta.1/source/theme=divisions/type=division/*.zstd.parquet', filename=true) LIMIT 1;
                  id = 085e50097fffffff01a76c1ccb5da39b
            geometry = \x00\x00\x00\x00\x01\xC0ah\xBA\xC7\x10\xCB)\xC0V\x7F\xDF;dZ\x1D
                bbox = {'xmin': -139.27281, 'xmax': -139.2728, 'ymin': -89.998, 'ymax': -89.997986}
             version = 0
         update_time = 2024-06-07T23:14:26Z
             sources = [{'property': , 'dataset': OpenStreetMap, 'record_id': N5314074411, 'confidence': NULL}]
             subtype = locality
            wikidata = Q243307
          population = 49
               names = {'primary': Amundsen-Scott Base, 'common': {en=Amundsen–Scott South Pole Station, hu=Amundsen-Scott kutatóállomás, mk=Станица Амундсен-Скот, zh=阿蒙森-斯科特南极站, zh-HanS=阿蒙森-斯科特南极站}, 'rules': [{'variant': official, 'language': NULL, 'value': Amundsen–Scott South Pole Station, 'between': NULL, 'side': NULL}, {'variant': alternate, 'language': en, 'value': Amundsen–Scott South Pole, 'between': NULL, 'side': NULL}]}
               class = 
           divisions = 
         is_disputed = 
        perspectives = 
          local_type = {en=village}
             country = AQ
              region = 
         hierarchies = [[{'division_id': 08522ae67fffffff01712c4916c9bc3b, 'subtype': country, 'name': Antarctica}, {'division_id': 085e50097fffffff01a76c1ccb5da39b, 'subtype': locality, 'name': Amundsen-Scott Base}]]
  parent_division_id = 08522ae67fffffff01712c4916c9bc3b
               norms = 
capital_division_ids = 
         division_id = 
            filename = /mnt/alpha/overture-2024-06-13-beta.1/source/theme=divisions/type=division/part-00000-1d99c024-2aa0-4441-981e-a13f5e4b0647-c000.zstd.parquet
               theme = divisions
                type = division

**Comment by jwass** [comment]
Hi. This is similar to #174. Each theme will contain all columns from other "type"s within the theme. This is something we'll fix, but you can safely ignore those extra fields as they should all be null.

I'll close this one and leave open #174

**Comment by ComeTogether1** [comment]
Ok. Thank you! 
There are several more layers with similar problems, maybe this will be fixed too.
If you suddenly need a list, I can write to you.
