### ISSUE TITLE
roof_height values missing from Building theme

### ISSUE THREAD

**Issue by jeffdefacto** [OvertureMaps/data#184]
July building data is missing all roof_height values due to a bug

**Comment by atiannicelli** [comment]
Fixed a bug where we were looking at roof_height tag instead of roof:height

https://github.com/OvertureMaps/tf-data-platform/pull/420

**Comment by jenningsanderson** [comment]
This is now a known issue in the July release and will be fixed in upcoming releases.

**Comment by atiannicelli** [comment]
fixed in https://github.com/OvertureMaps/tf-data-platform/pull/423
expected in August release

**Comment by skmoore** [comment]
I'm seeing some roof_height data in the July release:
![Screenshot 2024-07-29 at 8 58 51 AM](https://github.com/user-attachments/assets/f793acf2-e77d-4454-8452-d79b407e9fa2)
