### ISSUE TITLE
Missing buildings

### ISSUE THREAD

**Issue by iluvmemes** [OvertureMaps/data#188]
There may be missing data in the latest release.  I was testing a query of mine via Athena against 2024_07_22_0 and noticed that the building I had always been searching for (my house) was no longer present.  I verified it was still present in the previous release.  Here is my query:

```
WITH bbox_filter AS (
	SELECT id, geometry, bbox, sources
	FROM v2024_07_22_0 AS b
	WHERE theme = 'buildings'
    AND bbox.xmin <= -117.02478698989 + 0.001
    AND bbox.xmax >= -117.02478698989 - 0.001
    AND bbox.ymin <= 32.77367039639495 + 0.001
    AND bbox.ymax >= 32.77367039639495 - 0.001
)
SELECT *,
	ST_Area(
		to_spherical_geography(ST_GeomFromBinary(geometry))
	) AS area_square_meters,
	ST_Area(
		to_spherical_geography(ST_GeomFromBinary(geometry))
	) * 10.7639 AS area_square_feet
FROM bbox_filter
WHERE ST_CONTAINS(
		ST_GeomFromBinary(geometry),
		ST_Point(-117.02478698989, 32.77367039639495)
	);
```

Clearly, that's not my house (I live in SW Missouri), it's just there to show that the query is valid.

edit: typo

**Comment by jwass** [comment]
Hi @iluvmemes - I wonder if you're seeing the same issue as https://github.com/OvertureMaps/data/issues/143?

Do you use duckdb? I'm curious if the query like this gives you the correct results. If so, we'll know it's that Athena bug.
```
SELECT id, geometry, bbox, sources
      FROM read_parquet('s3://overturemaps-us-west-2/release/2024-07-22.0/theme=buildings/type=building/*.parquet')

      WHERE bbox.xmin <= -117.02478698989 + 0.001
      AND bbox.xmax >= -117.02478698989 - 0.001
      AND bbox.ymin <= 32.77367039639495 + 0.001
      AND bbox.ymax >= 32.77367039639495 - 0.001;
```

We also have this slick new website https://explore.overturemaps.org - more info https://docs.overturemaps.org/blog/2024/07/24/explore-site/. If you zoom in and your house is there, we'll know things are okay. You can also click on the building to get the id and search for it in that query above and then have it returned.

If you try those and that building is still missing, let us know because something would definitely be wrong in that case.

**Comment by iluvmemes** [comment]
Thanks for the reply @jwass and the suggestion.  I was able to find the building via the maps website and obtain the id.  After further checking, I'm pretty confident that the issue is with the geospacial functions in the where clause.  

I kept the bounding box CTE and then removed the where clause geospacial functions and just looked for the id value.  It found the record meaning it was indeed located in the filter.  This means that [#143](https://github.com/OvertureMaps/data/issues/143) isn't the issue.  Why this would differ between releases is still baffling me.

I compared the well known text of the geometry between both sets and they are identical.

```
WITH geom_analysis AS (
    SELECT 
        'v2024_06_13_beta_1' AS source_table,
        id, 
        bbox,
        ST_IsValid(ST_GeomFromBinary(geometry)) AS is_valid,
        ST_AsText(ST_Centroid(ST_GeomFromBinary(geometry))) AS centroid_text,
        ST_AsText(ST_GeomFromBinary(geometry)) AS geometry_wkt,
        ST_Area(to_spherical_geography(ST_GeomFromBinary(geometry))) AS area_square_meters
    FROM v2024_06_13_beta_1
    WHERE id = 'redacted'
    UNION ALL
    SELECT 
        'v2024_07_22_0' AS source_table,
        id, 
        bbox,
        ST_IsValid(ST_GeomFromBinary(geometry)) AS is_valid,
        ST_AsText(ST_Centroid(ST_GeomFromBinary(geometry))) AS centroid_text,
        ST_AsText(ST_GeomFromBinary(geometry)) AS geometry_wkt,
        ST_Area(to_spherical_geography(ST_GeomFromBinary(geometry))) AS area_square_meters
    FROM v2024_07_22_0
    WHERE id = 'redacted'
)
SELECT * FROM geom_analysis;
```

**Comment by jwass** [comment]
Choosing an id in that area - I can verify that duckdb returns the results using the bounding box but Athena does not. So I'm pretty sure this is the same as #143

**Comment by jwass** [comment]
Thanks to @mojodna, the fix as reported here https://github.com/OvertureMaps/data/discussions/1#discussioncomment-9159544 so I think your queries will just start reporting the right results now. They'll be a bit slower on Athena, but at least correct.

Let us know if that fixes things and we can close this.

**Comment by iluvmemes** [comment]
Yes, that does resolve the issue.  @jwass and @mojodna, thank you for all of your assistance.
