### ISSUE TITLE
No land_use point features in July release

### ISSUE THREAD

**Issue by skmoore** [OvertureMaps/data#194]
I'm not seeing any point `land_use` features in the July release. There are 1,975 in the June release.

![Screenshot 2024-07-26 at 3 49 42 PM](https://github.com/user-attachments/assets/eb4cf4e5-beef-47d1-a50f-642643b4d51d)

**Comment by jenningsanderson** [comment]
Correct — land_use currently only contains polygons and 1 type of linestring: `track=leisure`

Closing for now — can re-open this discussion in `base` meeting if we want to re-add point features?

Note that `land` does include some point features for natural places, like beaches.
