### ISSUE TITLE
Some ML buildings in Water

### ISSUE THREAD

**Issue by atiannicelli** [OvertureMaps/data#199]
ML buildings showing up along Chicago River 
https://explore.overturemaps.org/#19.16/41.8885334/-87.6254043

building id: 08b2664c1e2a6fff0200a046511038e6

**Comment by skmoore** [comment]
Also seeing some in the Seine River
![Screenshot 2024-08-06 at 2 27 27 PM](https://github.com/user-attachments/assets/60e85683-def8-425a-b8f6-77f6cb8f2038)

**Comment by skmoore** [comment]
And Chicago River: https://explore.overturemaps.org/#16.49/41.888754/-87.616944
![Screenshot 2024-08-06 at 4 02 16 PM](https://github.com/user-attachments/assets/38a45cb2-7ce3-4ebc-afca-39192653496e)

**Comment by skmoore** [comment]
And Lake Mead: https://explore.overturemaps.org/#14.87/36.10259/-114.69361

![Screenshot 2024-08-06 at 4 06 52 PM](https://github.com/user-attachments/assets/94bb0cbc-120c-42b4-a6a4-ea0e3e5983fd)

**Comment by skmoore** [comment]
Lake Michigan: https://explore.overturemaps.org/#17.06/41.901817/-87.615845

![Screenshot 2024-08-06 at 4 09 57 PM](https://github.com/user-attachments/assets/576d0c6b-ef32-4335-a07b-dcc64371eb3c)

**Comment by atiannicelli** [comment]
I found the issue, it was a mistake with the filtering algorithm. All buildings that cross water were being identified as needing to be excluded, but the filtering process to exclude was not reading the filter table correctly. So no buildings were filtered out. This is a regression in the July Release and it will be fixed in the August Release.

listing building gers IDs of some of the other buildings found in water to use to verify fix
08b2664c1e95efff0200ee51b966ab40
08b2986c4b11afff0200e7392c1e7456
08b2664c1e340fff0200b3608ac6e515

**Comment by atiannicelli** [comment]
I have validated, using the canary build, that MOST of the issues above have been fix by the change we made to the August release.
The area around [#14.87/36.10259/-114.69361](https://explore.overturemaps.org/#14.87/36.10259/-114.69361) looks good
The area around [#16.49/41.888754/-87.616944](https://explore.overturemaps.org/#16.49/41.888754/-87.616944) also looks good.

But unfortunately I still see 08b2664c1e95efff0200ee51b966ab40
here: [#17.06/41.901817/-87.615845](https://explore.overturemaps.org/#17.06/41.901817/-87.615845)

I'm going to close this bug and open another one to track that issue. I'm guessing there is something different with that water body
