### ISSUE TITLE
Missing buildings in a few areas

### ISSUE THREAD

**Issue by chaitanyach** [OvertureMaps/data#201]
I was comparing the July 2024 buildings, and I found some square tiles missing most of the buildings when compared to May. These tiles are at zoom level 15 of WMTS with Pseudo Mercator projection.
Here are some examples:

Most of the buildings missing in the tile at 26.268458N,80.107122W. They were present in May release.
![image-20240804-151656](https://github.com/user-attachments/assets/369bf212-9b0e-4fa7-98f6-251ca0786833)

A few tiles in a row near 32.80196N,117.17697W are missing most of the buildings (quadkey 023013221210301). Present in May release.
![image-20240804-152217](https://github.com/user-attachments/assets/07fa3d9a-5f23-49c8-8d9e-1f421c8ca3b3)

There are more such areas.

**Comment by skmoore** [comment]
@jenningsanderson I see this too, one example that was present in May and missing in June and July is 08b44a12b155efff020051dffb3f954d

**Comment by jenningsanderson** [comment]
Interesting. I don't see these features in OSM nor in Microsoft ML Building footprints. It looks like `08b44a12b155efff020051dffb3f954d` was an MSFT building from May but is not present in the newer data available from Microsoft.

Here's what I see in Rapid with MSFT ML turned on: 
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/62dceeac-c89b-4e33-9452-46d0865ca89d">

Odd that this particular square is empty. I can't seem to find deleted OSM features that used to be there, either.

**Comment by jfmartinez4** [comment]
I commented on #216 about missing data, and I wasn't sure if it was the data or something on my end. 
<img width="662" alt="Screenshot 2024-09-01 at 1 53 23 PM" src="https://github.com/user-attachments/assets/25941f45-d379-4d03-9010-c61d480f67ec">

**Comment by jenningsanderson** [comment]
> I commented on #216 about missing data, and I wasn't sure if it was the data or something on my end. <img alt="Screenshot 2024-09-01 at 1 53 23 PM" width="662" src="https://private-user-images.githubusercontent.com/104371759/363510652-25941f45-d379-4d03-9010-c61d480f67ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDE3NzksIm5iZiI6MTcyNTY0MTQ3OSwicGF0aCI6Ii8xMDQzNzE3NTkvMzYzNTEwNjUyLTI1OTQxZjQ1LWQzNzktNGQwMy05MDEwLWM2MWQ0ODBmNjdlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjUxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTE4NDEwZjRkNjY2MDdlNjhiZTMxZjAyMjFjMDAyM2Q5OTA4ZjlhNmRjMmIyMzQyMWQxM2JiZWZkMTQyNTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UnFON04dnCvA0KDcYX_vZr1z3nbmpxNISYPtJEl7oaU">

Here's the link to the explore site where the data is visible: https://explore.overturemaps.org/#14.11/38.091/-122.23557

Perhaps try using DuckDB or the Python CLI utility to download the data for this region again?

**Comment by jenningsanderson** [comment]
This particular issue seems to be coming from the MSFT ML buildings dataset — buildings that _were_ present before are no longer there.

**Comment by chaitanyach** [comment]
If a source dataset removes some buildings, are they assumed to no longer exist even if they exist in other sources?

**Comment by jenningsanderson** [comment]
@chaitanyach It would depend on which source _removed_ them. In this case, we don't have another source that has the buildings, so they are _gone_. However, current conflation logic would have it that if a building was _removed_ from a higher priority source (such as OSM / Esri), but still existed in a lower priority source (Microsoft, Google), then we would choose that building because we currently prioritize _coverage_. We recognize the error that this could introduce and are working on considering a building being _removed_ from a higher priority source as a _signal_ to not re-add the building from a lower priority source. Hope that helps!
