### ISSUE TITLE
Building and building_part missing column data

### ISSUE THREAD

**Issue by jeffdefacto** [OvertureMaps/data#204]
August release is missing almost all data for num_floors, min_floor, and num_floors_underground in both the building_part and building types.

**Comment by skmoore** [comment]
:grimacing:

**Comment by atiannicelli** [comment]
@skmoore does this make this release unusable for you guys?

**Comment by atiannicelli** [comment]
We have a fix: https://github.com/OvertureMaps/tf-data-platform/pull/473

**Comment by skmoore** [comment]
Will this fix make it into the August release?
