### ISSUE TITLE
AWS Glue Refusing connections?

### ISSUE THREAD

**Issue by honeybadger93** [OvertureMaps/data#205]
Hello,

I tried connecting to the data with Athena following the instructions [here](https://docs.overturemaps.org/getting-data/athena-aws/) but am getting an error "..Admin is not authorized to perform: glue:GetDatabases on resource: arn:aws:glue:us-east-2:913550007193:catalog because no resource-based policy allows the glue:GetDatabases action (Service: AmazonDataCatalog; Status Code: 400; Error Code: AccessDeniedException..."

Before I continue to troubleshoot on my end, I want to just double check here that the AWS account is still allowing incoming connections from Athena and isn't in maintenance or something?

Thanks!

**Comment by skmoore** [comment]
No issues for me right now.

**Comment by skmoore** [comment]
Did you explicitly grant access to the Overture Glue Data Catalog?

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "glue:GetTable*",
        "glue:GetDatabase*",
        "glue:GetPartition*"
      ],
      "Resource": [
        "arn:aws:glue:us-west-2:913550007193:catalog",
        "arn:aws:glue:us-west-2:913550007193:database/release",
        "arn:aws:glue:us-west-2:913550007193:table/*"
      ]
    }
  ]
}
```

**Comment by honeybadger93** [comment]
Yes I did.. I'll head back to snowflake for now and pick up troubleshooting Athena another time. I might just be overlooking something simple. Thanks

**Comment by skmoore** [comment]
You could try granting `glue:*` , that would at least tell you if it's a Glue permissions problem.

**Comment by honeybadger93** [comment]
I have that attached to my user as well, which is what made me think it might be on Overture's side. I have admin full access

**Comment by mojodna** [comment]
@honeybadger93 you're accessing it from a different region: `arn:aws:glue:**us-east-2**:913550007193:catalog`. Try from `us-west-2`.

**Comment by honeybadger93** [comment]
Thanks, that worked!! 
I misread the tip at the top of the doc and thought it said us-east-2. If it refuses connections from other regions, then it might be worth changing the wording from a Tip to a Prerequisite here to help others avoid running into that: https://docs.overturemaps.org/getting-data/athena-aws/
