### ISSUE TITLE
Latest table v2024_08_20_0 is missing previously available data

### ISSUE THREAD

**Issue by PetroTruemetrics** [OvertureMaps/data#215]
When running following query in Athena for tables `v2024_08_20_0` and `v2024_07_22_0`, I get completely different results and the latest table `v2024_08_20_0` seems to be much worse for at least my particular example location. Is this a bug?

Query:
```
select *, st_geomfrombinary(geometry) as geometry from v2024_07_22_0
where bbox.xmin > 9.79395893113965 and bbox.xmax < 9.80319929242982
and bbox.ymin > 51.81092833731859 and bbox.ymax < 51.81698782964098
and (theme = 'buildings' or type = 'building') 
```

`v2024_08_20_0` results:

<img width="1157" alt="image" src="https://github.com/user-attachments/assets/2a8a7233-8630-4e56-a4fd-2a4ca2e1db09">

`v2024_07_22_0` results:

<img width="1156" alt="image" src="https://github.com/user-attachments/assets/37e3a892-4551-4c01-820d-e2400e467176">

**Comment by jenningsanderson** [comment]
Hi @PetroTruemetrics, thanks for highlighting this — these buildings are indeed still there, you can see them on the explore page: https://explore.overturemaps.org/#17.98/51.813529/9.796483

Unfortunately, what you're running into is an Athena-specific bug related to bounding box queries that we are working on. 

These 400+ buildings are indeed in the August data in Athena if you match by ID: 

```sql
WITH july_ids AS (
	select id
	from v2024_07_22_0
	where bbox.xmin > 9.79395893113965
		and bbox.xmax < 9.80319929242982
		and bbox.ymin > 51.81092833731859
		and bbox.ymax < 51.81698782964098
		AND type = 'building'
)
SELECT *,
    st_geomfrombinary(geometry) as wkt
FROM v2024_08_20_0
	JOIN july_ids ON v2024_08_20_0.id = july_ids.id
```

**Comment by jenningsanderson** [comment]
@PetroTruemetrics — for reference, here's the Trino issue: https://github.com/trinodb/trino/issues/21754
