### ISSUE TITLE
Weird artefacts in buildings dataset

### ISSUE THREAD

**Issue by RaczeQ** [OvertureMaps/data#217]
I have downloaded a buildings dataset for Greater London (release `2024-08-20.0`) and noticed some strange artefacts looking like gaps around a rectangle.
![london_om_original_bbox](https://github.com/user-attachments/assets/377e4c11-f77a-427f-92a0-4bc444214205)

I've marked the area with orange squares:
![london_om_original_bbox_square](https://github.com/user-attachments/assets/7f951715-f344-46f9-8383-74e54531a0ec)

Those artefacts are also present in the release `2024-07-22.0`:
![london_bbox_old_release](https://github.com/user-attachments/assets/c59f76c5-9dcf-4636-8e24-516f1c26bca1)

**Comment by jwass** [comment]
Hi @RaczeQ - I was looking on our explore site (https://explore.overturemaps.org/#11.76/51.4197/0.0107)
 around the area you're calling out.

At a first glance, it seems like many of the buildings in this area are from Microsoft ML buildings - which we use to fill in gaps from OSM. So this might be an artifact of their satellite coverage or other processing. I don't think we have a great viewer of the MS ML data to fully verify it yet.

 Can you provide coordinates of one of those smaller rectangles where it appears data is missing?

**Comment by RaczeQ** [comment]
I've located some example here:

https://explore.overturemaps.org/#14.89/51.42615/-0.00494
https://www.openstreetmap.org/search?query=51.42505%2C%20-0.00517#map=16/51.42636/-0.00526
https://www.google.com/maps/@51.4248394,-0.0079453,17z

It seemed like there are missing buildings also in the OpenStreetMap dataset 🤔 ?

![image](https://github.com/user-attachments/assets/02fe6a1a-10a2-442f-b4d1-34fd88b2e8a5)
![image](https://github.com/user-attachments/assets/0196d7b2-8210-4b91-a6ff-9b0d137946fc)
![image](https://github.com/user-attachments/assets/909e30d1-102f-43b5-bf5b-a8e1302e17bb)

**Comment by RaczeQ** [comment]
I've also downloaded OSM buildings for the same area (`{'building':True}`) and I can't see such artefacts here:
![london_osm_buildings](https://github.com/user-attachments/assets/c1efd0e9-b207-4c2a-a90e-391e466d133c)

**Comment by RaczeQ** [comment]
![london_om_coloured_full](https://github.com/user-attachments/assets/9356a8a3-341d-4ea9-8d01-13fcbc5b7d0d)
I've also coloured the datasets based on the source (OSM - blue vs MS ML buildings - orange) and it seems like it's an issue with Microsoft ML buildings dataset.

**Comment by atiannicelli** [comment]
I used Rapid to look at one of the spots you highlighted and it appears that the Microsoft Buildings Dataset does indeed have some gaps that appear to be along the edges of zoom 15 tiles. Specifically I can see that the following quadkeys seems to have no Microsoft Buildings:
031313131100002, 031313131100020, 031313131100022, 031313131100200, 031313131100202, and on down that row until you get to 031313131102202

Here is how I got there. First I used Rapid to zoom in and I turned off everything except for buildings. Red buildings are OSM, and Maroon buildings are Microsoft.
https://rapideditor.org/rapid#map=15.73/51.5870/-0.3431&background=MAPNIK&datasets=msBuildings&disable_features=points,traffic_roads,service_roads,paths,indoor,landuse,boundaries,water,rail,pistes,aerialways,power,past_future,others
<img width="1792" alt="Screenshot 2024-09-04 at 9 43 11 AM" src="https://github.com/user-attachments/assets/f3a918c2-05fd-44b9-baaa-c5838a421834">

Then I found that location on What the tile to try to figure out if it followed a tile boundary.
go to https://labs.mapbox.com/what-the-tile/  and then search for the quadkey: 031313131100200 
and then zoom out until you get to zoom 15. 
<img width="1492" alt="Screenshot 2024-09-04 at 9 45 50 AM" src="https://github.com/user-attachments/assets/146bfcf8-dcb0-41c9-ab2a-03bc531ce8ae">

You can see by comparing the two sites that the Microsoft buildings, visible on Rapid when the "Microsoft Buildings" feature is turned on, have a gap and there are not that many OSM buildings in that area (although there are some).

The Overture Explorer shows a similar gap. https://explore.overturemaps.org/#14.89/51.58464/-0.3456
<img width="1792" alt="Screenshot 2024-09-04 at 9 48 25 AM" src="https://github.com/user-attachments/assets/4f2416a5-3cf4-4941-aab0-d605926b9090">

So, this is definitely a gap in the Microsoft buildings data. Also of note is that the What's my Tile site, when you zoom in a bit, shows buildings in that area... so now I'm interested in knowing where they got their buildings data from.

**Comment by RaczeQ** [comment]
Mapbox probably has their own provider of source data for tiles.

**Comment by andwoi** [comment]
This is an artifact of how we merge two sets of buildings processed at different times. We don't have a great way to know when a structure was removed so when we process a tile we assume the whole area was updated and drop buildings from the lower priority set.  The alternative is we could check tile updates and building intersection and only drop older buildings when we have one to replace it with. We see errors with this later technique when imagery registration shifts structures which also creates unsatisfying updates. We're open to other suggestions as well!
