### ISSUE TITLE
Not able to download data

### ISSUE THREAD

**Issue by snuup** [OvertureMaps/data#224]
My Azure Experience is this:

![image](https://github.com/user-attachments/assets/92f0d12f-126f-496d-8cf6-4aaffdf6e9e0)

WIth S3 I did not managed it either.

I would like to avoid account password hassles.

I would like to download via a link, the same way as I download OSM planet files.

Is that possible? The Python tool does extracts only as far as aI see.

Why do you make that so difficult?

**Comment by snuup** [comment]
The S3 experience is this:

aws s3api get-object --bucket s3://overturemaps-us-west-2/release/2024-08-20.0/theme=places/type=place/ .

error: ... key missing ...

**Comment by snuup** [comment]
I tried 

     aws s3 sync s3://overturemaps-us-west-2/release/2024-08-20.0/theme=places/type=place/ .

which does not allow me to inspect the size that I have to reserve on my disk, as I have no clue about the file size. It also, until now, returns a list of 100+ error messages, "Directory os not readable" ...

Data Download is ridiculous here atm.

**Comment by mtravis** [comment]
@snuup you should be able to use `aws s3 ls s3://overturemaps-us-west-2/release/2024-08-20.0/theme=places/type=place/ --summarize --human-readable` 

I can't test that myself right now as not at my machine but hopefully it should work. I think the Places dataset is less than 10GB though.

**Comment by mtravis** [comment]
> I tried
> 
> ```
>  aws s3 sync s3://overturemaps-us-west-2/release/2024-08-20.0/theme=places/type=place/ .
> ```
> 
> which does not allow me to inspect the size that I have to reserve on my disk, as I have no clue about the file size. It also, until now, returns a list of 100+ error messages, "Directory os not readable" ...
> 
> Data Download is ridiculous here atm.

Try using `aws s3 cp` instead of sync

**Comment by snuup** [comment]
After syncing with an empty local directory I managed to download the places-parquet file. I cannot see any reason why that file is not available on a plain http server with directory browsing switched on. Would have saved me the time to enter hundred keys passwords and investigate cloud tools.

**Comment by jwass** [comment]
@snuup Glad you were able to get the data.

Overture is not distributed like OSM as a single file. An OSM planet PBF - as hosted by planet.openstreetmap.org is 77GB. Overture data is currently around 450GB. We know some teams want to download it all, some want just the roads or places (like in your case), other people want all data only limited to a single region. It's difficult to provide files that meet everybody's needs. Instead we offer the tooling that can download what you need. It's a different approach than what many people are used where you can download a single file.

**Comment by snuup** [comment]
The places datafile that I was interested in is 4.5 GB. Placing a 450GB for download also is not a serious thing. OSM also has larger versions of the planet file AFAIR. But thank you so much for making this data available.

**Comment by wiseHolmes** [comment]
> @snuup Glad you were able to get the data.
> 
> Overture is not distributed like OSM as a single file. An OSM planet PBF - as hosted by planet.openstreetmap.org is 77GB. Overture data is currently around 450GB. We know some teams want to download it all, some want just the roads or places (like in your case), other people want all data only limited to a single region. It's difficult to provide files that meet everybody's needs. Instead we offer the tooling that can download what you need. It's a different approach than what many people are used where you can download a single file.

You could talk to the OSM guys. They could probably help with compression and file formats.

**Comment by mtravis** [comment]
> > @snuup Glad you were able to get the data.
> > Overture is not distributed like OSM as a single file. An OSM planet PBF - as hosted by planet.openstreetmap.org is 77GB. Overture data is currently around 450GB. We know some teams want to download it all, some want just the roads or places (like in your case), other people want all data only limited to a single region. It's difficult to provide files that meet everybody's needs. Instead we offer the tooling that can download what you need. It's a different approach than what many people are used where you can download a single file.
> 
> You could talk to the OSM guys. They could probably help with compression and file formats.

@snuup @wiseHolmes FWIW, having the data stored in geoparquet, which is binary an compressed, allows a user to analyse the data quickly and easily using a range of tools without having to acutally download. 

From my experience working with PBFs was a bit clunky as you need to convert to other formats. You can extract the Overturemaps data for a whole country and drop the file straight into QGIS.

**Comment by mryang9118** [comment]
I tested 
[aws s3 ls s3://overturemaps-us-west-2/release/2024-08-20.0/theme=places/type=place/ --summarize --human-readable](url)

and got the error message:
An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.

**Comment by jenningsanderson** [comment]
@mryang9118 — You'll want to add `--no-sign-request` to that command:

```
aws --no-sign-request s3 ls s3://overturemaps-us-west-2/release/2024-08-20.0/theme=places/type=place/ --summarize --human-readable
```

**Comment by mryang9118** [comment]
> @mryang9118 — You'll want to add `--no-sign-request` to that command:
> 
> ```
> aws --no-sign-request s3 ls s3://overturemaps-us-west-2/release/2024-08-20.0/theme=places/type=place/ --summarize --human-readable
> ```

thanks, it works!
