### ISSUE TITLE
Hierarchies missing from Divisions (division_area)

### ISSUE THREAD

**Issue by laumz** [OvertureMaps/data#247]
Hierarchies field is empty from 9/18 and 10/23 releases in USA?

**Comment by stepps00** [comment]
Hi @laumz the hierarchies column should be present and contain hierarchy data for divisions features in both of these releases. Example query using DuckDB:

```
SELECT
  hierarchies
FROM
  read_parquet('s3://overturemaps-us-west-2/release/2024-10-23.0/theme=divisions/type=division/*', filename=true, hive_partitioning=1)
WHERE
  country = 'US'
LIMIT 10;
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                     hierarchies                                                     │
│                          struct(division_id varchar, subtype varchar, "name" varchar)[][]                           │
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ [[{'division_id': 0850c861bfffffff01aeb407d56d3441, 'subtype': country, 'name': United States}, {'division_id': 0…  │
│ [[{'division_id': 0850c861bfffffff01aeb407d56d3441, 'subtype': country, 'name': United States}, {'division_id': 0…  │
│ [[{'division_id': 0850c861bfffffff01aeb407d56d3441, 'subtype': country, 'name': United States}, {'division_id': 0…  │
│ [[{'division_id': 0850c861bfffffff01aeb407d56d3441, 'subtype': country, 'name': United States}, {'division_id': 0…  │
│ [[{'division_id': 0850c861bfffffff01aeb407d56d3441, 'subtype': country, 'name': United States}, {'division_id': 0…  │
│ [[{'division_id': 0850c861bfffffff01aeb407d56d3441, 'subtype': country, 'name': United States}, {'division_id': 0…  │
│ [[{'division_id': 0850c861bfffffff01aeb407d56d3441, 'subtype': country, 'name': United States}, {'division_id': 0…  │
│ [[{'division_id': 0850c861bfffffff01aeb407d56d3441, 'subtype': country, 'name': United States}, {'division_id': 0…  │
│ [[{'division_id': 0850c861bfffffff01aeb407d56d3441, 'subtype': country, 'name': United States}, {'division_id': 0…  │
│ [[{'division_id': 0850c861bfffffff01aeb407d56d3441, 'subtype': country, 'name': United States}, {'division_id': 0…  │
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                       10 rows                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Would you mind pasting your query so we can help debug?

**Comment by laumz** [comment]
Sorry, it is actually division_area that seems to have null values for the hierarchies field?

SELECT
  hierarchies
FROM
  read_parquet('s3://overturemaps-us-west-2/release/2024-10-23.0/theme=divisions/type=division_area/*', filename=true, hive_partitioning=1)
WHERE
  country = 'US'
LIMIT 10;
┌──────────────────────────────────────────────────────────────────┐
│                           hierarchies                            │
│ struct(division_id varchar, subtype varchar, "name" varchar)[][] │
├──────────────────────────────────────────────────────────────────┤
│ NULL                                                             │
│ NULL                                                             │
│ NULL                                                             │
│ NULL                                                             │
│ NULL                                                             │
│ NULL                                                             │
│ NULL                                                             │
│ NULL                                                             │
│ NULL                                                             │
│ NULL                                                             │
├──────────────────────────────────────────────────────────────────┤
│                             10 rows                              │
└──────────────────────────────────────────────────────────────────┘
