### ISSUE TITLE
OSM foot paths being displayed as roads in Overture

### ISSUE THREAD

**Issue by aardrop** [OvertureMaps/data#263]
Missing tags and metadata from OSM in Overture seem to show footpaths like trails, tracks, and paths as roads. 

Below is an example, but I looked over multiple continents to confirm it's a persistent issue. I can't check at the data layer yet, only in the explorer levels.

<img width="1512" alt="Screenshot 2024-12-21 at 10 20 24 AM" src="https://github.com/user-attachments/assets/236faa0f-8a09-473b-a920-ec8109385021" />
https://explore.overturemaps.org/#16.83/39.998959/-105.28488

<img width="1512" alt="Screenshot 2024-12-21 at 10 19 42 AM" src="https://github.com/user-attachments/assets/36998695-2f45-4b9f-bd95-264b6fe62f09" />
https://www.openstreetmap.org/way/217337067

Here, you can see that the overture lacks context on certain metadata, such as foot and cycle, and some of the metadata attached to the OSM path indicates its usage other than "unpaved."

Is this an issue or out of the scope of what Overture is trying to do? We work with municipalities and regional governments to publicly manage and provide their spatial data. We would love to explore Overture more, but this would prevent us from being able to use Overture.

**Comment by brad-richardson** [comment]
It looks like you closed this so you may have figured it out, but `road` is just the subtype, which is basically the set of all land transportation. The `class`/`subclass`/`subclass_rules` attributes carry the more detailed [classification](https://docs.overturemaps.org/schema/concepts/by-theme/transportation/roads/#road-class) you're looking for. 

There are other tags from OSM we don't yet have Overture schema to capture, so please let us know what else you see missing to help us steer priorities!
