### ISSUE TITLE
Downloads via AWS CLI result in very small (possibly incomplete) amounts of data

### ISSUE THREAD

**Issue by s1mpson** [OvertureMaps/data#27]
## I'm trying to download the full **Admins subset** of OvertureMaps data.

I'm using the exact command displayed in [README](https://github.com/OvertureMaps/data#4-download-the-parquet-files) with Amazon S3 Admins data location from the table at the top of the page:

```sh
aws s3 cp --region us-west-2 --no-sign-request --recursive s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins <DESTINATION>
```

During the process, it shows that there are only **656.9 MiB** in total to download, which already seems too small for geo data:
<pre>Completed 347.3 MiB/656.9 MiB (10.3 MiB/s) with 18 file(s) remaining</pre>

<details>
<summary><i>The command completes with no errors.</i></summary>
<pre>
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_3b7d7eb3-dd9c-442a-a9b9-404dc936c5d9 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_3b7d7eb3-dd9c-442a-a9b9-404dc
936c5d9
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_10dcb45e-6078-4875-8a88-52d12f8ab8c5 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_10dcb45e-6078-4875-8a88-52d12
f8ab8c5
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_1744f6c1-a9f1-44ad-b857-25450cbe5f84 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_1744f6c1-a9f1-44ad-b857-25450
cbe5f84
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_493c0769-00a9-46cb-a86c-d92badfde317 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_493c0769-00a9-46cb-a86c-d92ba
dfde317
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_0c3a0082-4509-4d9a-812c-a88574c248c8 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_0c3a0082-4509-4d9a-812c-a8857
4c248c8
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_4560cc21-a7e0-40e7-bebe-2d19db445d10 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_4560cc21-a7e0-40e7-bebe-2d19d
b445d10
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_57472892-d4fa-4c25-ba3e-7a76da30f311 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_57472892-d4fa-4c25-ba3e-7a76d
a30f311
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_6194f239-f53a-4f7a-a18d-844d65743ec5 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_6194f239-f53a-4f7a-a18d-844d6
5743ec5
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_396e41da-f316-4502-ae56-32f9317e6383 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_396e41da-f316-4502-ae56-32f93
17e6383
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_61f7299b-3606-4181-a7c6-69ea1aac3a28 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_61f7299b-3606-4181-a7c6-69ea1
aac3a28
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_b0b8f7e1-cfa0-461c-8bc8-3f5cdd91c89a to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_b0b8f7e1-cfa0-461c-8bc8-3f5cd
d91c89a
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_7c7218a6-5008-4639-8dd1-83c3dd339843 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_7c7218a6-5008-4639-8dd1-83c3d
d339843
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_7f63afbc-a937-4a81-a641-76b1c4873382 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_7f63afbc-a937-4a81-a641-76b1c
4873382
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_49005169-4d7b-4ce6-94bd-4d78d022b7f0 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_49005169-4d7b-4ce6-94bd-4d78d
022b7f0
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_0100b1b9-31ab-4d03-9a92-8141dcae93a5 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_0100b1b9-31ab-4d03-9a92-8141d
cae93a5
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_a6909589-1b62-42a0-9a8f-b1eb2f1c5098 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_a6909589-1b62-42a0-9a8f-b1eb2
f1c5098
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_93613538-4394-423c-9801-e78bd9990077 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_93613538-4394-423c-9801-e78bd
9990077
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_7dc54ea9-ab92-4741-8dae-56fa8593fe87 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_7dc54ea9-ab92-4741-8dae-56fa8
593fe87
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_b629fbf5-9571-4ff1-8db6-f813a16157d0 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_b629fbf5-9571-4ff1-8db6-f813a
16157d0
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_a374e245-14d8-4d98-a405-9b15caddfad6 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_a374e245-14d8-4d98-a405-9b15c
addfad6
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_c5c77b7b-e0de-4001-af9b-a3627c32cce7 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_c5c77b7b-e0de-4001-af9b-a3627
c32cce7
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_c31fcd15-d578-45ed-bdff-739415154198 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_c31fcd15-d578-45ed-bdff-73941
5154198
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_d0765388-e086-474a-9d5a-c15cb2c08176 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_d0765388-e086-474a-9d5a-c15cb
2c08176
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_beb3ee79-4796-4088-b92f-2c48c80c4143 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_beb3ee79-4796-4088-b92f-2c48c
80c4143
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_d3e98a46-301e-49c7-a9d7-ca3c80c0a8d8 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_d3e98a46-301e-49c7-a9d7-ca3c8
0c0a8d8
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_c045daa2-19ca-42cf-8fb2-0a29d9142116 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_c045daa2-19ca-42cf-8fb2-0a29d
9142116
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_699b878b-12d3-4229-bdea-3d473a4c2161 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_699b878b-12d3-4229-bdea-3d473
a4c2161
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_efa7e14e-b7cc-403e-84c9-29b6343dabf8 to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_efa7e14e-b7cc-403e-84c9-29b63
43dabf8
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_2a32a61f-fde0-44d0-92a0-da19890fe6d5 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_2a32a61f-fde0-44d0-92a0-da19890fe6d5
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_38ef7a79-a2c5-4fbc-900b-4da561907b35 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_38ef7a79-a2c5-4fbc-900b-4da561907b35
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_fef965a3-b003-48f8-8188-1c8c7b233ccb to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_fef965a3-b003-48f8-8188-1c8c7
b233ccb
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=administrativeBoundary/20230725_211237_00132_5p54t_fd2a04db-9317-4cfd-b02e-b7a4337dc91d to E:\Variant1\type=administrativeBoundary\20230725_211237_00132_5p54t_fd2a04db-9317-4cfd-b02e-b7a43
37dc91d
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_27c6842b-85ea-4c1b-8557-6bf624ef40eb to E:\Variant1\type=locality\20230725_211237_00132_5p54t_27c6842b-85ea-4c1b-8557-6bf624ef40eb
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_0fa79fec-7a39-4f51-90a6-aa94b553befd to E:\Variant1\type=locality\20230725_211237_00132_5p54t_0fa79fec-7a39-4f51-90a6-aa94b553befd
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_25816df1-b864-49c0-a9a3-a13da4f37a90 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_25816df1-b864-49c0-a9a3-a13da4f37a90
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_44dfa1f2-b07c-4849-ab40-1161237ee7ba to E:\Variant1\type=locality\20230725_211237_00132_5p54t_44dfa1f2-b07c-4849-ab40-1161237ee7ba
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_364a3443-0868-44ce-a1fa-080c875f569b to E:\Variant1\type=locality\20230725_211237_00132_5p54t_364a3443-0868-44ce-a1fa-080c875f569b
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_66f751a6-909f-4f62-a882-8fc52e9c6070 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_66f751a6-909f-4f62-a882-8fc52e9c6070
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_2d36b134-7e29-4b30-9820-2e96cec914c6 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_2d36b134-7e29-4b30-9820-2e96cec914c6
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_863b0a4b-3b99-4ce4-81e6-14bd6d2e7900 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_863b0a4b-3b99-4ce4-81e6-14bd6d2e7900
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_50659010-f73e-418d-9073-43e09ed1340e to E:\Variant1\type=locality\20230725_211237_00132_5p54t_50659010-f73e-418d-9073-43e09ed1340e
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_3ab157c6-65e2-45f5-8755-5fc3616da69c to E:\Variant1\type=locality\20230725_211237_00132_5p54t_3ab157c6-65e2-45f5-8755-5fc3616da69c
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_8bc41f71-e2e5-414d-8b8b-47838b38b47c to E:\Variant1\type=locality\20230725_211237_00132_5p54t_8bc41f71-e2e5-414d-8b8b-47838b38b47c
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_9be940e5-0894-4273-9b70-0cc6c7125e78 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_9be940e5-0894-4273-9b70-0cc6c7125e78
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_8ec97150-2af9-4f95-b8d4-3d1069b9b9b1 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_8ec97150-2af9-4f95-b8d4-3d1069b9b9b1
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_9834870f-1352-4cd8-b368-dddedcb60492 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_9834870f-1352-4cd8-b368-dddedcb60492
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_a09f88de-3255-44db-96fc-58240eacd2b4 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_a09f88de-3255-44db-96fc-58240eacd2b4
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_bdd68c0b-c1cc-426b-a425-c6003252c2d9 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_bdd68c0b-c1cc-426b-a425-c6003252c2d9
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_a7dc6141-7682-48e0-8abb-4fa50160e3d4 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_a7dc6141-7682-48e0-8abb-4fa50160e3d4
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_c0b1ebbb-5dd2-4129-bcaa-d3a3c6995da0 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_c0b1ebbb-5dd2-4129-bcaa-d3a3c6995da0
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_c030ff2c-f89d-4b2f-87e7-f443fa7c1b20 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_c030ff2c-f89d-4b2f-87e7-f443fa7c1b20
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_a7a2923e-eef8-4af0-9c73-9873d5ec4b5b to E:\Variant1\type=locality\20230725_211237_00132_5p54t_a7a2923e-eef8-4af0-9c73-9873d5ec4b5b
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_d74f9d4a-54d2-4035-9f7b-651353a3934e to E:\Variant1\type=locality\20230725_211237_00132_5p54t_d74f9d4a-54d2-4035-9f7b-651353a3934e
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_d5a9dd57-f533-466c-b1cd-928ef84d1307 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_d5a9dd57-f533-466c-b1cd-928ef84d1307
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_d61c9b8c-1222-4835-a115-f45614a31b6a to E:\Variant1\type=locality\20230725_211237_00132_5p54t_d61c9b8c-1222-4835-a115-f45614a31b6a
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_c1c26ebb-625f-4e96-9b34-bee82321e24f to E:\Variant1\type=locality\20230725_211237_00132_5p54t_c1c26ebb-625f-4e96-9b34-bee82321e24f
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_e608b636-1b9e-4e3c-ad00-d93fb09ed323 to E:\Variant1\type=locality\20230725_211237_00132_5p54t_e608b636-1b9e-4e3c-ad00-d93fb09ed323
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_e3dabde9-bfcb-43f1-9398-b88a15b6561a to E:\Variant1\type=locality\20230725_211237_00132_5p54t_e3dabde9-bfcb-43f1-9398-b88a15b6561a
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_e8e4e379-51ad-43e8-887b-e727eddaf13f to E:\Variant1\type=locality\20230725_211237_00132_5p54t_e8e4e379-51ad-43e8-887b-e727eddaf13f
download: s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins/type=locality/20230725_211237_00132_5p54t_eb1d890c-bf41-455d-8c69-0418dbfa6deb to E:\Variant1\type=locality\20230725_211237_00132_5p54t_eb1d890c-bf41-455d-8c69-0418dbfa6deb
</pre>
</details>

Everything was downloaded "as expected" with **665 MB** on disk.

Upon closer inspection by loading all the Parquet files into DuckDB with the following query:

```sql
SELECT * FROM read_parquet(['./type=locality/*.','./type=administrativeBoundary/*']);
```

I find out there are only **~96,000 rows (~4,000 from `type=locality`)**.

I could not find any statistic on how many rows there should be (which definitely must be included in the documentation), but judging from my personal experience these numbers are way off the point (it's around 3,000,000 localities in OSM).

**Comment by jenningsanderson** [comment]
Good observation, not all admin levels are present in the alpha.0 release, so 96k rows is the correct row count.
