### ISSUE TITLE
Are there any Python/DuckDB code examples?

### ISSUE THREAD

**Issue by arnoudbuzing** [OvertureMaps/data#31]
Are there any Python/DuckDB code examples, for example to load places in a certain bounding box?

**Comment by arnoudbuzing** [comment]
For example, I downloaded the places like so:

aws s3 cp --region us-west-2 --no-sign-request --recursive s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=places ~/Downloads/overture/

But this gave me a number of files like this:

% ls -1
20230725_210643_00079_ayc64_01c760ca-02aa-4387-8b71-b2eaa6c7c700
20230725_210643_00079_ayc64_023fe3f2-d72a-40b6-9eb9-4bb1b61664d6
20230725_210643_00079_ayc64_15b8943c-63b7-45c8-99fd-82a63affb530

So what is the next step to access them?

**Comment by arnoudbuzing** [comment]
I can do something like this, but then I am stuck:

>>> db = duckdb.read_parquet('~/Downloads/overture/type=place/*')
>>> db
┌──────────────────────┬──────────────────────┬─────────┬──────────────────────┬───┬──────────────────────┬──────────────────────┬──────────────────────┬──────────────────────┐
│          id          │      updatetime      │ version │        names         │ … │      addresses       │       sources        │         bbox         │       geometry       │
│       varchar        │       varchar        │  int32  │ map(varchar, map(v…  │   │ map(varchar, varch…  │ map(varchar, varch…  │ struct(minx double…  │         blob         │
├──────────────────────┼──────────────────────┼─────────┼──────────────────────┼───┼──────────────────────┼──────────────────────┼──────────────────────┼──────────────────────┤
│ tmp_95150E1B603F21…  │ 2023-07-24T00:00:0…  │       0 │ {common=[{value=Qu…  │ … │ [{locality=Ho Chi …  │ [{dataset=meta, pr…  │ {'minx': 106.81380…  │ \x01\x01\x00\x00\x…  │
│ tmp_29D9A8F44B8976…  │ 2023-07-24T00:00:0…  │       0 │ {common=[{value=Su…  │ … │ [{locality=Tasikma…  │ [{dataset=meta, pr…  │ {'minx': 108.23156…  │ \x01\x01\x00\x00\x…  │
│ tmp_734B83D4FAD250…  │ 2023-07-24T00:00:0…  │       0 │ {common=[{value=Sd…  │ … │ [{locality=Airbang…  │ [{dataset=meta, pr…  │ {'minx': 99.377452…  │ \x01\x01\x00\x00\x…  │
│ tmp_0C683419260652…  │ 2023-07-24T00:00:0

**Comment by bertt** [comment]
See https://bertt.wordpress.com/2023/07/31/overture-maps/

**Comment by arnoudbuzing** [comment]
Okay, thanks Bert, that looks promising!!
