### ISSUE TITLE
AWS Athena instructions not clear or wrong

### ISSUE THREAD

**Issue by cbeddow** [OvertureMaps/data#32]
When I run the queries:

1) if I run both the CREATE EXTERNAL TABLE and the MSCK REPAIR TABLE, I get `line 1:8: mismatched input 'EXTERNAL'. Expecting: 'MATERIALIZED', 'OR', 'ROLE', 'SCHEMA', 'TABLE', 'VIEW'`

2) The instructions say only one query at a time in Athena. So if I run just one part of that query, only CREATE EXTERNAL TABLE, then it works. But then I get no partitions loaded. Running MSCK REPAIR TABLE `places`; yields:

```
line 1:1: mismatched input 'MSCK'. Expecting: 'ALTER', 'ANALYZE', 'CALL', 'COMMENT', 'COMMIT', 'CREATE', 'DEALLOCATE', 'DELETE', 'DENY', 'DESC', 'DESCRIBE', 'DROP', 'EXECUTE', 'EXPLAIN', 'GRANT', 'INSERT', 'MERGE', 'PREPARE', 'REFRESH', 'RESET', 'REVOKE', 'ROLLBACK', 'SET', 'SHOW', 'START', 'TRUNCATE', 'UNLOAD', 'UPDATE', 'USE', <query>
```

3) If I also just click the places table options and click on `Load partitions` same result as in step 2

Conclusion: following the exact instructions does not yield expected results. If you do have a way around this, please let me know, but my expectation is that following the literal instructions should work here.

**Comment by cbeddow** [comment]
@jenningsanderson do you know if region has effects on this? Should be a same problem with Daylight if trying to load different regions?

**Comment by jenningsanderson** [comment]
Thanks @cbeddow, added!
