### ISSUE TITLE
Typo in locality schema: defaultlanugage should be defaultlanguage

### ISSUE THREAD

**Issue by arnoudbuzing** [OvertureMaps/data#34]
Typo in locality schema: defaultlanugage should be defaultlanguage

D describe localities;
┌──────────────────────┬────────────────────────────────────────────────────────────┬─────────┬─────────┬─────────┬───────┐
│     column_name      │                        column_type                         │  null   │   key   │ default │ extra │
│       varchar        │                          varchar                           │ varchar │ varchar │ varchar │ int32 │
├──────────────────────┼────────────────────────────────────────────────────────────┼─────────┼─────────┼─────────┼───────┤
│ id                   │ VARCHAR                                                    │ YES     │         │         │       │
│ updatetime           │ VARCHAR                                                    │ YES     │         │         │       │
│ version              │ INTEGER                                                    │ YES     │         │         │       │
│ names                │ MAP(VARCHAR, MAP(VARCHAR, VARCHAR)[])                      │ YES     │         │         │       │
│ adminlevel           │ INTEGER                                                    │ YES     │         │         │       │
│ maritime             │ VARCHAR                                                    │ YES     │         │         │       │
│ subtype              │ VARCHAR                                                    │ YES     │         │         │       │
│ localitytype         │ VARCHAR                                                    │ YES     │         │         │       │
│ context              │ VARCHAR                                                    │ YES     │         │         │       │
│ isocountrycodealpha2 │ VARCHAR                                                    │ YES     │         │         │       │
│ isosubcountrycode    │ VARCHAR                                                    │ YES     │         │         │       │
│ **defaultlanugage**      │ VARCHAR                                                    │ YES     │         │         │       │
│ drivingside          │ VARCHAR                                                    │ YES     │         │         │       │
│ sources              │ MAP(VARCHAR, VARCHAR)[]                                    │ YES     │         │         │       │
│ bbox                 │ STRUCT(minx DOUBLE, maxx DOUBLE, miny DOUBLE, maxy DOUBLE) │ YES     │         │         │       │
│ geometry             │ BLOB                                                       │ YES     │         │         │       │
│ type                 │ VARCHAR                                                    │ YES     │         │         │       │
├──────────────────────┴────────────────────────────────────────────────────────────┴─────────┴─────────┴─────────┴───────┤
│ 17 rows                                                                                                       6 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
D

**Comment by jenningsanderson** [comment]
Fixed in 2023-10-19
