### ISSUE TITLE
`recordId` vs. `recordid`

### ISSUE THREAD

**Issue by msbarry** [OvertureMaps/data#40]
The "source" field of some elements has the key `recordid` (all lower case) but other elements have the key `recordId` (upper case I).

I discovered this when parsing overture data with planetiler and had to add this workaround:

https://github.com/onthegomap/planetiler/blob/15b939b2b717d804e7d2fb50f0be8d25e0d466b9/planetiler-core/src/main/java/com/onthegomap/planetiler/overture/OvertureSchema.java#L609-L615

**Comment by jenningsanderson** [comment]
As of 2023-10-19, an entry in `sources` is represented as a `struct` instead of a `map<string,string>` in the parquet files, so it is now consistent: 

```sql
sources: array<struct<property:string,dataset:string,recordId:string,confidence:double>>
```
