### ISSUE TITLE
Inconsistent `createdAt` format

### ISSUE THREAD

**Issue by msbarry** [OvertureMaps/data#41]
The "createdAt" field of some elements is expressed as an INT96 timestamp, but others are expressed as a UTC date time string.  

I discovered this when parsing overture data with planetiler and had to add this workaround:

https://github.com/onthegomap/planetiler/blob/15b939b2b717d804e7d2fb50f0be8d25e0d466b9/planetiler-core/src/main/java/com/onthegomap/planetiler/overture/OvertureSchema.java#L593

Also INT96 appears to be deprecated, could it just be conveyed as 64-bit milliseconds since epoch or something like that?

**Comment by jenningsanderson** [comment]
Closing as resolved in the `beta` release; please re-open if this is still an issue
