### ISSUE TITLE
`road` field is just a JSON string

### ISSUE THREAD

**Issue by msbarry** [OvertureMaps/data#43]
While implementing the planetiler overture schema I noticed that `road` attribute of transportation segments is just a JSON string, whereas everything else is structured. Is this intentional?

**Comment by jenningsanderson** [comment]
Yes, this is intentional at the moment because of the complexity and nesting of the fields. However, changing this is on the to-do list!

**Comment by BruceHarold** [comment]
This is still the case at the beta release

**Comment by msbarry** [comment]
@jenningsanderson if this is going to be the long term path forward, would you consider using the JSON logical annotation on the road column? Right now it is just "string":

```
D select name, type, logical_type from  parquet_schema('s3://overturemaps-us-west-2/release/2024-05-16-beta.0/theme=transportation/type=segment/part-00000-75974d59-da36-4d39-b487-f70371da3f6c-c000.zstd.parquet') where name='road';
┌─────────┬────────────┬──────────────┐
│  name   │    type    │ logical_type │
│ varchar │  varchar   │   varchar    │
├─────────┼────────────┼──────────────┤
│ road    │ BYTE_ARRAY │ StringType() │
└─────────┴────────────┴──────────────┘

```

**Comment by BruceHarold** [comment]
> @jenningsanderson if this is going to be the schema going forward, would you consider using the JSON logical annotation on the road column? Right now it is just "string":
> 
> ```
> D select name, type, logical_type from  parquet_schema('s3://overturemaps-us-west-2/release/2024-05-16-beta.0/theme=transportation/type=segment/part-00000-75974d59-da36-4d39-b487-f70371da3f6c-c000.zstd.parquet') where name='road';
> ┌─────────┬────────────┬──────────────┐
> │  name   │    type    │ logical_type │
> │ varchar │  varchar   │   varchar    │
> ├─────────┼────────────┼──────────────┤
> │ road    │ BYTE_ARRAY │ StringType() │
> └─────────┴────────────┴──────────────┘
> ```

I parse it OK from string.
`# Create an extract table of the road object's speed limits
conn.sql("""create or replace temp table extract as (select id,
                                                     json_extract(road,'$.restrictions.speed_limits') as speed_limits
                                                     from segments where speed_limits is not null);""")`

**Comment by msbarry** [comment]
Yeah, it's not a blocker, I'm just implementing geoparquet support for planetiler and having the extra metadata enables some more functionality for the reader.  It would help duckdb too so you could read values like this:

```
D select road.surface from  read_parquet('s3://overturemaps-us-west-2/release/2024-05-16-beta.0/theme=transportation/type=segment/*') limit 10;
Binder Error: Cannot extract field 'surface' from expression "road" because it is not a struct, union, or json
```

**Comment by BruceHarold** [comment]
> Yeah, it's not a blocker, whil implementing geoparquet support for planetiler I'm finding that the extra metadata enables some more functionality for the reader. It would help duckdb too so you could read values like this:
> 
> ```
> D select road.surface from  read_parquet('s3://overturemaps-us-west-2/release/2024-05-16-beta.0/theme=transportation/type=segment/*') limit 10;
> Binder Error: Cannot extract field 'surface' from expression "road" because it is not a struct, union, or json
> ```

Oh yeah, I see what you mean.  We'll see what June brings!

**Comment by vcschapp** [comment]
Overture's Transportation and Schema TFs are moving ahead pretty quickly with fixing this issue. We want to make sure that all the road data follow a structured Parquet schema ASAP. (The JSON `road` was always meant to be temporary.)

I believe the goal is to get this issue fixed for the mid-June data release, falling back to the July release if we miss June.

As a preliminary, we merged [a schema PR](https://github.com/OvertureMaps/schema/pull/203) on Wednesday that flattens the road segment schema by lifting up a number of more deeply nested properties to the top level (they will become their own dedicated Parquet columns). We hope this is one last increment of churn in the transportation schema before we can achieve stability.

These new road schema columns, when populated, will have a structured Parquet schema. We hope to have them populated in June, but as I said, if we miss they should be there by July. At that point we'll drop the old `road` property and transportation will have a nice structured Parquet schema going forward.
