### ISSUE TITLE
Questions about Overture 2023-07-26-alpha.0

### ISSUE THREAD

**Issue by Issacs00** [OvertureMaps/data#58]
Hi, This is Issacs from Inavisystems, which is in South Korea.
 
We checked Overture 2023-07-26-alpha.0, released by the Overture Map Foundation on July 26, 2023.
 
After checking the release, we have two questions about attribute data.
 
The questions are as below.
 
1. Are there different data attributes for each country? 
When we checked Overture 2023-07-26-alpha.0, which first-release version of open map data on July 26, we found that only 'Road name' and 'Road class' are available among the Korean data attributes. So we are wondering if other countries have also released only those attributes data.
 
2. If we become a member of the Overture maps Foundation as a Contributor, can we get more attribute data (ex. Traffic Information, Speed Limit, Lane, Rest Stop, Detour, etc.)  than is released to the public in Overture 2023-07-26-alpha.0?
 
Please comment on our question. 
 
Have a great day ahead.

**Comment by jwass** [comment]
Hi @Issacs00  - We are reviewing some old issues. It's been 8 months and there's been quite a bit of work on the transportation schema - please consult the latest schema and documentation. I'll close this for now but feel free to re-open or start a new issue with any remaining questions.
