### ISSUE TITLE
Open Overtone Data in GIS

### ISSUE THREAD

**Issue by MarjanNikoukar** [OvertureMaps/data#65]
Hi, I just want to know what is the best way to open overtune boundary data in GIS. Can I download the GeoParquet file and open it in QGIS? Or is there any better way to convert the Parquet file to a shapefile for opening in GIS?
I really appreciate it if you explain both options if applicable.

**Comment by mtravis** [comment]
@MarjanNikoukar 

Take have a look at the comments in this discussion.

https://github.com/OvertureMaps/data/discussions/62#discussioncomment-6965363

The data held here isn't actually in Geoparquet format but plain parquet with the geometry stored as as well known binary. You can actually grab the data in Geoparquet format here: https://beta.source.coop/cholmes/overture

You should be able to open in QGIS in later versions but the data will be read-only.

**Comment by MarjanNikoukar** [comment]
Thank you so much for your assistance. I am gonna check.

**Comment by MarjanNikoukar** [comment]
Hello @mtravis. I downloaded the Geoparquet file and opened it in QGIS. Thank you so much for your help.
Now, I need this data in the shapefile format. What do you think is the best way?

**Comment by Youssef-Harby** [comment]
@MarjanNikoukar, Can you share why you want the data in Shapefile format? Shapefiles have some downsides, so I usually suggest using other formats. 

### How to Convert Using QGIS
If you really need it in Shapefile, here’s how you can do it using QGIS:

#### Step 1: Start Export
- Find the layer you want, right-click on it, and go to `Export` > `Save Features As...`:
   ![Start Export](https://github.com/OvertureMaps/data/assets/13020265/24220ebd-22c0-438d-950b-8b68cb7fb955)

#### Step 2: Pick Format and Name Your File
- Pick `ESRI Shapefile` from the ‘Format’ list and don’t forget to give your file a name before saving it:
   ![Pick Format](https://github.com/OvertureMaps/data/assets/13020265/d6c3ba8d-0c98-4a16-8e1f-0445f3e00cea)

### Warning
Remember, Shapefiles have their own problems, so think about if you really need this format, or if another one might work better for you.

### Additional Information
If you are planning to use this data in ArcGIS Pro, the GeoPackage format may also suit your needs for reading the data. However, please note that data in GeoPackage format is not editable in ArcGIS Pro.

**Comment by bglazer-meta** [comment]
looks like you all figured this out. please feel free to re-open as needed.
