### ISSUE TITLE
"Transportation Theme" in Overture 2023-10-19-alpha.0

### ISSUE THREAD

**Issue by Issacs00** [OvertureMaps/data#73]
Hi, I have a question regarding the "Transportation Theme" in Overture 2023-10-19-alpha.0. 
In this version, as mentioned, the 'Transportation Theme' section has some missing properties, such as:

 Non-geometric scoping properties
 Turn and Access restrictions 
 Lane information
 Some language/scripts in names properties

So, the question is whether the Overture Maps Foundation has a detailed release plan for adding this missing information. 
If we get information about the this plan, it will be invaluable to our business planning and future. 
Look forward to your response.
Thank you for your time and consideration.

**Comment by jwass** [comment]
It's been 8 months and there's been quite a bit of work on the transportation schema - please consult the latest schema and documentation. I'll close this for now but feel free to re-open or start a new issue with any remaining questions.
