### ISSUE TITLE
Error when copying the whole dataset via aws s3 cli

### ISSUE THREAD

**Issue by mtravis** [OvertureMaps/data#75]
I've been trying to download the whole dataset to see how it's partitnioned but I'm getting this error 
`fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied`

when using
 
`aws s3 cp  --region us-west-2 --no-sign-request --recursive s3://overturemaps-us-west-2/release/2023-10-19-alpha.0/  . `

Should it also be possible to use `aws s3 ls` on the dataset? 

Thanks

**Comment by jwass** [comment]
Does `aws --no-sign-request s3 cp ...` work?

**Comment by mtravis** [comment]
Not for me. I've tried lots of different options now.

**Comment by jwass** [comment]
` aws --no-sign-request s3 ls s3://overturemaps-us-west-2/release/2023-10-19-alpha.0/` does not work for you?

Or is it just `cp` that doesn't work?

**Comment by jwass** [comment]
@mojodna Any thoughts?

**Comment by mtravis** [comment]
Ok, so it appears to be working (both cp & ls) on a remote Ec2 instance but not on my laptop.

Where I'm seeing `An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied`

**Comment by jwass** [comment]
@mtravis Did this get resolved? Okay to close?

**Comment by mtravis** [comment]
@jwass this seems to be working now thanks.
