### ISSUE TITLE
Slow query in Duckdb?

### ISSUE THREAD

**Issue by bertt** [OvertureMaps/data#8]
Hi, I'm executing this query in Duckdb (v0.8.1):

```
SELECT ST_GeomFromWkb(geometry) AS geometry, JSON(names) AS names
from  read_parquet('s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=places/type=*/*', filename=true, hive_partitioning=1)
where bbox.minX > 5.1 and bbox.maxX < 5.2 and bbox.minY > 52.1 and bbox.maxY < 52.2 ;
```

But it's very slow (an hour +) for retrieving only 2049 points....

Q: Is the bbox struct properly indexed? Or is there an other way to speed up?

**Comment by dkgaraujo** [comment]
I also noted duckdb seems to pull all data first before filtering. By the way it doesn’t seem like it is caching the local version so it could at least speed up further queries.

**Comment by jiayuasu** [comment]
Hi folks, if you are in rush to download a small portion of the data using the exact shape of a region, please give Apache Sedona + GeoParquet + Geospatial filter pushdown a try. See my answer here: https://github.com/OvertureMaps/data/discussions/3#discussioncomment-6800002

**Comment by bertt** [comment]
Hi @jiayuasu I tried in DuckDb, it's much better - about 7.5 minutes (but you have to know the geohex code):

```
D select count(*) from parquet_Scan('s3://wherobots-public-data/overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=buildings/type=building/geohash=u1/*') where bbox.minX > 5.1 and bbox.maxX < 5.2 and bbox.minY > 52.1 and bbox.maxY < 52.2 ;
```

**Comment by OscarD31** [comment]
Hi. I've just faced the same problem. Several hours to get the buildings of a small area.

What is that geohex code you have mentioned?

**Comment by bertt** [comment]
it's a 2 digit code (in this case) you can get it at https://www.movable-type.co.uk/scripts/geohash.html

**Comment by jiayuasu** [comment]
@bertt @OscarD31 If you want to stick to DuckDB, just run the exact same query (note that I am using the Wherobots version data)

```
SELECT ST_GeomFromWkb(geometry) AS geometry, JSON(names) AS names
from  read_parquet('s3://wherobots-public-data/overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=places/type=*/*', filename=true, hive_partitioning=1)
where bbox.minX > 5.1 and bbox.maxX < 5.2 and bbox.minY > 52.1 and bbox.maxY < 52.2 ;
```

It should be done in a few minutes. The magic behind that is Apache Sedona (https://github.com/apache/sedona) groups data by their spatial proximity as well. Again, my blog post explained everything: https://medium.com/@dr.jiayu/harnessing-overture-maps-data-apache-sedonas-journey-from-parquet-to-geoparquet-d99f7767a499

**Comment by bglazer-meta** [comment]
looks like you all figured this out. please feel free to re-open as needed. - look out for improvements in H2 2023.

**Comment by Maxxen** [comment]
Working on resolving the struct-filter-pushdown issue [here](https://github.com/duckdb/duckdb/pull/10314)!

**Comment by bertt** [comment]
tried in 0.10, from 1 hour + to 3 minutes, good job!

![image](https://github.com/OvertureMaps/data/assets/538812/747ef957-b287-4433-9b24-43d13df6845b)

**Comment by jwass** [comment]
Awesome! Thank you for following up ~7 months!
