### ISSUE TITLE
Typo in Athena example table for Admins 

### ISSUE THREAD

**Issue by mtravis** [OvertureMaps/data#80]
Incorrect spelling in this line. https://github.com/OvertureMaps/data/blob/main/athena_setup_queries.sql#L83C1-L83C28

**Comment by jenningsanderson** [comment]
Unfortunately that is an error in the actual data from the July release. These queries are only relevant for that release — the 2023-10-19.alpha.0 release has the correct spelling.

**Comment by jenningsanderson** [comment]
Ah, you're right! Sorry about that, I have updated the queries.
