### ISSUE TITLE
Using Overture Maps dataset in a legal way

### ISSUE THREAD

**Issue by SongMY11** [OvertureMaps/data#84]
Hi, I am writing to ask that I want to use Overture map dataset in my company for some data research and may use it on company internal products or even commercial use in future, what should I do to use this dataset in a legal way. Should I pay for it to get your permission or some other things? 

Thanks a lot for your help in advance and looking forward to your response.

**Comment by SongMY11** [comment]
@mprioleau Hi Marc, sorry to bother you, but this question is really important to me. Could you please view this question and give your reply? Thanks a lot in advance.

**Comment by mprioleau** [comment]
Hell @SongMY11 , Overture map data is open data, licensed under either CDLA Permissive 2.0 or ODbL, depending on the data type.Please see the release notes to see which license applies to which themes. 
You do not need to pay to download and use the data.  However, there are attribution and share alike requirements for the ODbL license.  I would encourage you to review the license requirements here:
CDLA Permissive v 2.0: https://cdla.dev/permissive-2-0/
ODbL: https://opendatacommons.org/licenses/odbl/summary/
