### ISSUE TITLE
Canada boundaries are wrong

### ISSUE THREAD

**Issue by akhenakh** [OvertureMaps/data#9]
<img width="296" alt="Screenshot 2023-07-26 at 4 26 40 PM" src="https://github.com/OvertureMaps/data/assets/218430/fffda77e-6f72-41a8-ab18-86df8588c655">

**Comment by varapmsft** [comment]
Thanks for the feedback. We will investigate and fix this issue in a future release.

**Comment by jenningsanderson** [comment]
Fixed in 2023-10-19 release.
