### ISSUE TITLE
Document sources

### ISSUE THREAD

**Issue by Cj-Malone** [OvertureMaps/data#92]
Some of the sources are kinda documented on in [release notes](https://overturemaps.org/download/overture-november-2023-release-notes/), but it's hard to understand.

It'd be nice it documented in an easy to read way.

(The below is just a starting point, from my limited understanding, I'm not involved with Overture) 

```mermaid
flowchart TD
    OSM(OpenStreetMap)
    Daylight(Daylight)
    MetaRoads(Facebook ML Roads)
    OvertureTransportation(Overture Transportation)

    OSM --> Daylight
    MetaRoads --> Daylight
    Daylight --> OvertureTransportation
```
```mermaid
flowchart TD
    OSM(OpenStreetMap)
    Daylight(Daylight)
    OvertureBase(Overture Base)

    OSM --> Daylight
    Daylight --> OvertureBase
```
```mermaid
flowchart TD
    OSM(OpenStreetMap)
    Daylight(Daylight)
    EsriCommunityMaps(Esri Community Maps)
    GoogleBuildings(Google Buildings)
    MicrosoftBuildings(Microsoft ML Building Footprints)
    USGS3DEP(USGS 3D Elevation Program)
    OvertureBuildings(Overture Buildings)

    OSM --> Daylight
    EsriCommunityMaps --> Daylight
    MicrosoftBuildings --> Daylight
    Daylight --> OvertureBuildings
    GoogleBuildings --> OvertureBuildings
    USGS3DEP --> OvertureBuildings
```
```mermaid
flowchart TD
    Microsoft(Microsoft)
    Meta(Facebook Places)
    OverturePlaces(Overture Places)

    Microsoft --> OverturePlaces
    Meta --> OverturePlaces
```
```mermaid
flowchart TD
    OSM(OpenStreetMap)
    Daylight(Daylight)
    OvertureAdministrativeBoundaries(Overture Administrative Boundaries)
    Esri(Esri)

    OSM --> Daylight
    Daylight --> OvertureAdministrativeBoundaries
    Esri --> OvertureAdministrativeBoundaries
```

**Comment by jwass** [comment]
Thanks. Overture records contain the sources that are all used to create a record. 

While not exactly the data flow diagram you're looking for, you can find which sources are used in which layers. Here's an Athena query that will get you most of it.
```
select theme,
	t.source.dataset,
	count(1) AS n
from overture_2023_11_14_alpha_0
	cross join unnest(sources) as t(source)
group by theme,
	t.source.dataset
order by theme,
    count(1) desc,
	t.source.dataset
```

```
#	theme	dataset	n
1	admins	OpenStreetMap	4702841
2	admins	Esri Community Maps	80472
3	base	OpenStreetMap	148174476
4	buildings	Microsoft ML Buildings	798633837
5	buildings	OpenStreetMap	579131416
6	buildings	Esri Community Maps	14280694
7	buildings	USGS Lidar	9096941
8	buildings	Denver Regional Council of Governments 2D Buildings	38663
9	buildings	Portland Building Footprint 2D Buildings	9824
10	buildings	Esri Buildings | Denver Regional Council of Governments 2D Buildings	9228
11	buildings	Miami-Dade County Open Data 3D Buildings	1786
12	buildings	NYC Open Data 3D Buildings	1087
13	buildings	Austin Building Footprints Year 2013 2D Buildings	923
14	buildings	Washington DC Open Data 3D Buildings	202
15	buildings	Boston BPDA 3D Buildings	157
16	buildings	Esri Buildings | Austin Building Footprints Year 2013 2D Buildings	117
17	buildings	City of Cambridge, MA Open Data 3D Buildings	45
18	places	meta	54004020
19	places	msft	13053921
20	transportation	OpenStreetMap	636701199
```

Note there are a few different ways that we refer to the same dataset which we are fixing. Also, some features have contributions from multiple sources - a good example is buildings might have a footprint from OSM but the height is derived from USGS Lidar using that footprint. This only contains a count. But the individual records have the information on them.

**Comment by jwass** [comment]
@Cj-Malone Building on that - you can find each individual record.

For example here are buildings that are comprised of more than 1 source:
```
select *
from overture_2023_11_14_alpha_0
where theme = 'buildings'
	and cardinality(sources) > 1
```

**Comment by Cj-Malone** [comment]
That's really interesting, thanks for the numbers.

So if I see an issue with a building with `source.dataset=City of Cambridge, MA Open Data 3D Buildings`, or if the height from USGS Lidar is wrong, how can I fix that?

**Comment by jwass** [comment]
The best way to fix just about anything right now is to improve it in OSM. In general, and especially for buildings, OSM takes top priority during conflation against any other source.

If OSM has a footprint and say Cambridge has one too, OSM's will be used directly. If OSM has a height, we will use that in place of any Lidar-derived one.

Short answer: fix it in OSM and it will find its way into Overture in the next release or two.

**Comment by Cj-Malone** [comment]
Awesome. I think the priority should be documented as well.

**Comment by jwass** [comment]
Thanks. Conflation order is mentioned in the release notes: https://overturemaps.org/download/overture-november-2023-release-notes/. See the second bullet in the buildings section.

I'm sure there's a better way - but that will probably be the best place to understand how each release gets built.
