### ISSUE TITLE
amazon road data

### ISSUE THREAD

**Issue by justinelliotmeyers** [OvertureMaps/data#95]
can amazon share its tracks within overture?

**Comment by mojodna** [comment]
Within Overture's data production process? Potentially. We're continuously working with Overture members to determine what signals they have that can be used to improve the dataset while respecting privacy and legal boundaries.

As part of an Overture data release? No, same as any other raw inputs we use to produce the data. Overture creates map products, so I wouldn't expect to see raw data included in any release.

**Comment by justinelliotmeyers** [comment]
Thanks, appreciate the feedback and explanation.
